name: Build & Deploy Unity 6  (Windows runner)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # 1️⃣  Clonar el repositorio
    - uses: actions/checkout@v3

    # 2️⃣  Instalar y activar Unity 6000.0.29f1
    - name: Set up Unity 6000.0.29f1
      uses: game-ci/unity-setup@v3          # ← versión correcta
      with:
        unityVersion: 6000.0.29f1           # tu editor
      env:
        UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    # 3️⃣  Compilar el servidor (headless, Windows)
    - name: Build headless server
      shell: pwsh
      run: |
        & "C:\Program Files\Unity\Hub\Editor\6000.0.29f1\Editor\Unity.exe" `
          -batchmode -nographics -quit `
          -projectPath . `
          -executeMethod BuildScript.PerformServerBuild
      env:
        UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    # 4️⃣  Subir el build completo al VPS
    - name: Upload build to VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        host:     ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key:      ${{ secrets.SSH_PRIVATE_KEY }}
        source:   "buildServer/**"
        target:   "/home/${{ secrets.SERVER_USER }}/server"

    # 5️⃣  Reiniciar servicio remoto
    - name: Restart game service
      uses: appleboy/ssh-action@v1.0.0
      with:
        host:     ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key:      ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart mygame-server
