name: Build & Deploy Unity 6  (Windows runner)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    env:
      UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    steps:
    - uses: actions/checkout@v3

    # Instala y activa Unity 6
    - name: Setup Unity 6000.0.29f1
      uses: game-ci/unity-setup@v3
      with:
        unityVersion: 6000.0.29f1            # tu versión exacta

    # Compila headless; deja el build en buildServer/
    - name: Build headless server
      shell: pwsh
      run: |
        & "C:\Program Files\Unity\Hub\Editor\6000.0.29f1\Editor\Unity.exe" `
          -batchmode -nographics -quit `
          -projectPath . `
          -executeMethod BuildScript.PerformServerBuild

    # Copia todo el build al VPS
    - name: Upload build to VPS
      uses: appleboy/scp-action@v0.1.5
      with:
        host:     ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key:      ${{ secrets.SSH_PRIVATE_KEY }}
        source:   "buildServer/**"
        target:   "/home/${{ secrets.SERVER_USER }}/server"

    # Reinicia tu servicio (usa Wine si VPS es Linux)
    - name: Restart game service
      uses: appleboy/ssh-action@v1.0.0
      with:
        host:     ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key:      ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart mygame-server
